/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Education = IDL.Record({
  'institution' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'degree' : IDL.Text,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'tools' : IDL.Vec(IDL.Text),
  'githubLink' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Skill = IDL.Record({
  'name' : IDL.Text,
  'proficiency' : IDL.Nat,
  'category' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'linkedin' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'github' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEducation' : IDL.Func([Education], [], []),
  'addProject' : IDL.Func([Project], [], []),
  'addSkill' : IDL.Func([Skill], [], []),
  'getAllEducation' : IDL.Func([], [IDL.Vec(Education)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getAllTools' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getProjectsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'getSkillsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Skill)], ['query']),
  'getSkillsByProficiency' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'updateProfile' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Education = IDL.Record({
    'institution' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'degree' : IDL.Text,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'tools' : IDL.Vec(IDL.Text),
    'githubLink' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Skill = IDL.Record({
    'name' : IDL.Text,
    'proficiency' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'linkedin' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'github' : IDL.Text,
  });
  
  return IDL.Service({
    'addEducation' : IDL.Func([Education], [], []),
    'addProject' : IDL.Func([Project], [], []),
    'addSkill' : IDL.Func([Skill], [], []),
    'getAllEducation' : IDL.Func([], [IDL.Vec(Education)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getAllTools' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getProjectsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getSkillsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Skill)], ['query']),
    'getSkillsByProficiency' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'updateProfile' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };