/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Education {
  'institution' : string,
  'year' : bigint,
  'description' : string,
  'degree' : string,
}
export interface Profile {
  'bio' : string,
  'linkedin' : string,
  'name' : string,
  'email' : string,
  'github' : string,
}
export interface Project {
  'title' : string,
  'tools' : Array<string>,
  'githubLink' : string,
  'description' : string,
  'category' : string,
}
export interface Skill {
  'name' : string,
  'proficiency' : bigint,
  'category' : string,
}
export interface _SERVICE {
  'addEducation' : ActorMethod<[Education], undefined>,
  'addProject' : ActorMethod<[Project], undefined>,
  'addSkill' : ActorMethod<[Skill], undefined>,
  'getAllEducation' : ActorMethod<[], Array<Education>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllSkills' : ActorMethod<[], Array<Skill>>,
  'getAllTools' : ActorMethod<[], Array<string>>,
  'getProfile' : ActorMethod<[], Profile>,
  'getProjectsByCategory' : ActorMethod<[string], Array<Project>>,
  'getSkillsByCategory' : ActorMethod<[string], Array<Skill>>,
  'getSkillsByProficiency' : ActorMethod<[], Array<Skill>>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];